version: "3.9"

services:
  app:
    image: ghcr.io/aaafasf/steven1:3.0.0
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"

        # Dominio
        - "traefik.http.routers.steven.rule=Host(`steven.byronrm.com`)"
        - "traefik.http.routers.steven.entrypoints=websecure"
        - "traefik.http.routers.steven.tls.certresolver=myresolver"

        # Servicio interno
        - "traefik.http.services.steven.loadbalancer.server.port=1001"

networks:
  traefik-public:
    external: true
